### ISSUE TITLE
Orion PEP proxy + Keycloak IDM

### ISSUE THREAD

**Issue by dc-1984** [SAF2/documentation#19]
Hello, I'd like to ask whether: 

a) either of the two available PEP proxies for Orion (i.e. either /fiware-orion-pep or /fi-ware-pep-proxy) can use Keycloak's IDM instead of Keystone's ?

b) if not, are there plans to make this functionality available? 

Thank you,
Dimitris

**Comment by JanWillemKruize** [comment]
Hi, I think that your question relates to the specific GE of the Orion Context broker. You probably have asked it already at the stackoverflow site as I see this post there:

http://stackoverflow.com/questions/29561163/fiware-orion-pepproxy 

Does this resolve your problem?

**Comment by dc-1984** [comment]
Hi Jan, thank you for your reply. That is not my question in stack overflow, and no, it doesn't relate to the specific GE of the Orion Context broker. The question in stack exchange relates to connecting the PEP proxy with Orion and FI-LAB. I want to connect the PEP proxy with Orion and FISpace. The problem is not in the connection between the proxy and Orion, but between the proxy and FISpace.
Please let me know if you require further information. Thank you.

**Comment by rapw3k** [comment]
Hi Dimitris,
I posted your question in stackoverflow:
http://stackoverflow.com/questions/30238211/orion-keycloak-idm 

I am copying the answer:
"I'm afraid they aren't. About the inclusion in the roadmap, it is not expected AFAIK, at least in 'fiware-orion-pep'. There are means, though, to integrate Keystone with other authentication providers (SAML, OpenID...), so maybe you should try to integrate THROUGH Keystone instead of replacing it with other authentication provider"

If this solves your questions, please close the issue

**Comment by dc-1984** [comment]
OK, thanks Raul. I have a follow-up question that I posted in stackoverflow. I'll let you know as soon as its answered, to close the issue.

**Comment by rapw3k** [comment]
Im closing this issue based on the finished discussion in stackoverflow.

**Comment by dc-1984** [comment]
Thank you Raul, I couldn't close it with my account
